version: "3.6"

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
    
services:
  aggregator-microservice:
    image: aggregator-microservice
    container_name: aggregator-microservice
    ports: 
      - 5000:5000
      
  database-microservice:
    image: database-microservice
    container_name: database-microservice
    ports: 
      - 23050:23050
    depends_on:
      - mysqldb
      
  search-microservice:
    image: search-microservice
    container_name: search-microservice
    ports: 
      - 23051:23051
    depends_on:
    - mysqldb
    - spark-master
    
  newsfeed-microservice:
    image: newsfeed-microservice
    container_name: newsfeed-microservice
    ports: 
      - 23052:23052
    depends_on:
    - mysqldb

  job-application-microservice:
    image: job-application-microservice
    container_name: job-application-microservice
    ports: 
      - 23053:23053
    depends_on:
    - mongodb
    - kafka

  notification-microservice:
    image: notification-microservice
    container_name: notification-microservice
    ports: 
      - 23054:23054
    depends_on:
    - mysqldb
    - kafka
    
  idm-microservice:
    image: idm-microservice
    container_name: idm-microservice
    ports: 
      - 8090:8090
    depends_on:
    - mysqldb
      
  mysqldb:
    platform: linux/x86_64
    container_name: mysqldb
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: daniel
      MYSQL_PASSWORD: daniel
      MYSQL_ROOT_PASSWORD: daniel
      
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27018:27017
         
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
      
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
      
  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
      
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
